export const typeOptions = [
  { title: "Film", value: "Film" },
  { title: "Short Film", value: "Short Film" },
  { title: "Documentary", value: "Documentary" },
  { title: "TV Series", value: "TV Series" },
  { title: "HollyWood", value: "HollyWood" },
  { title: "BollyWood", value: "BollyWood" },
  { title: "NollyWood", value: "NollyWood" },
  { title: "Music Video", value: "Music Video" },
  { title: "Music", value: "Music" },
  { title: "Bill Board", value: "Bill Board" },
  { title: "Video", value: "Video" },
  { title: "News", value: "News" },
  { title: "School Gist", value: "School Gist" },
];

export const statusOptions = [
  { title: "Public", value: "public" },
  { title: "Private", value: "private" },
];

export const languageOptions = [
  { title: "Bengali", value: "Bengali" },
  { title: "Chinese", value: "Chinese" },
  { title: "Czech", value: "Czech" },
  { title: "English", value: "English" },
  { title: "French", value: "French" },
  { title: "German", value: "German" },
  { title: "Gujarati", value: "Gujarati" },
  { title: "Hindi", value: "Hindi" },
  { title: "Italian", value: "Italian" },
  { title: "Igbo", value: "Igbo" },
  { title: "Indonesian", value: "Indonesian" },
  { title: "Japanese", value: "Japanese" },
  { title: "Korean", value: "Korean" },
  { title: "Marathi", value: "Marathi" },
  { title: "Maithili", value: "Maithili" },
  { title: "Nepali", value: "Nepali" },
  { title: "Odia", value: "Odia" },
  { title: "Polish", value: "Polish" },
  { title: "Portuguese", value: "Portuguese" },
  { title: "Russian", value: "Russian" },
  { title: "Spanish", value: "Spanish" },
  { title: "Tamil", value: "Tamil" },
  { title: "Telugu", value: "Telugu" },
  { title: "Turkish", value: "Turkish" },
  { title: "Ukrainian", value: "Ukrainian" },
  { title: "Vietnamese", value: "Vietnamese" },
];
